tkinter - Exemplos

In [1]:
from tkinter import Tk

janela_principal=Tk()
janela_principal.title('Eu sou a janela principal')
janela_principal.mainloop()

In [2]:
from tkinter import *
from tkinter import ttk

def calculate(*args):
    try:
        value = float(feet.get())
        meters.set(round(0.3048 * value, 4))
    except ValueError:
        pass

root = Tk()
root.title("Feet to Meters")

mainframe = ttk.Frame(root, padding=(3, 3, 12, 12))
mainframe.grid(column=0, row=0, sticky=(N, W, E, S))

feet = StringVar()
feet_entry = ttk.Entry(mainframe, width=7, textvariable=feet)
feet_entry.grid(column=2, row=1, sticky=(W, E))

meters = StringVar()
ttk.Label(mainframe, textvariable=meters).grid(column=2, row=2, sticky=(W, E))

ttk.Button(mainframe, text="Calculate", command=calculate).grid(column=3, row=3, sticky=W)

ttk.Label(mainframe, text="feet").grid(column=3, row=1, sticky=W)
ttk.Label(mainframe, text="is equivalent to").grid(column=1, row=2, sticky=E)
ttk.Label(mainframe, text="meters").grid(column=3, row=2, sticky=W)

root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
mainframe.columnconfigure(2, weight=1)
for child in mainframe.winfo_children(): 
    child.grid_configure(padx=5, pady=5)

feet_entry.focus()
root.bind("<Return>", calculate)

root.mainloop()

Pandas - Utilização desta Biblioteca

In [5]:
import sys
!"{sys.executable}" -m pip install pandas


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 4.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 4.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.9 MB 4.9 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 5.3 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 5.4 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 5.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.5 MB/s  0:00:01
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 5.5 MB/s eta 0:00:03
   ------- --------------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import sys
!"{sys.executable}" -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------------- ---------- 1.3/1.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 4.8 MB/s  0:00:00


In [5]:
import pandas as pd
#Criação do dicionário alunos com suas notas
alunos = {'Nome':['Maria', 'Pedro', 'Carla'],
          'Nota':[13,8,16],
          'Nota Final':['Aprovado', 'Reprovado', 'Aprovado']}

#Converter o dicionário numa Dataframe de Pandas
df_alunos=pd.DataFrame(alunos)
print(alunos)
print(df_alunos)

AttributeError: partially initialized module 'pandas' from 'C:\Users\User\AppData\Roaming\Python\Python314\site-packages\pandas\__init__.py' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

In [1]:
import pandas as pd

excel_dados = pd.read_excel('C:/Python/excel_dados.xlsx')

print(excel_dados.head(3))
print(excel_dados.tail(3))

     Carimbo       Data      Hora
0     Aceito 2026-02-15  12:55:25
1  Rejeitado 2026-02-16  13:55:25
2  Rejeitado 2026-02-17  14:55:25
     Carimbo       Data      Hora
7  Rejeitado 2026-02-22  19:55:25
8     Aceito 2026-02-23  20:55:25
9     Aceito 2026-02-24  21:55:25


In [2]:
print(excel_dados ['Carimbo'])

0       Aceito
1    Rejeitado
2    Rejeitado
3    Rejeitado
4       Aceito
5    Rejeitado
6    Rejeitado
7    Rejeitado
8       Aceito
9       Aceito
Name: Carimbo, dtype: str


In [4]:
print(excel_dados ['Carimbo'],['Data'])

0       Aceito
1    Rejeitado
2    Rejeitado
3    Rejeitado
4       Aceito
5    Rejeitado
6    Rejeitado
7    Rejeitado
8       Aceito
9       Aceito
Name: Carimbo, dtype: str ['Data']


In [7]:
print(excel_dados[excel_dados['Data'] > pd.Timestamp('2026-02-20')])

     Carimbo       Data      Hora
6  Rejeitado 2026-02-21  18:55:25
7  Rejeitado 2026-02-22  19:55:25
8     Aceito 2026-02-23  20:55:25
9     Aceito 2026-02-24  21:55:25


Pandas - uma coluna (tipo Série); mais de uma coluna Tipo Dataframe

In [9]:
import pandas as pd

excel_dados = pd.read_excel('C:/Python/excel_dados.xlsx')
vagas=excel_dados['Candidatura']
print (vagas.head(4))

0        Atendimento
1              Caixa
2      Contabilidade
3    Suporte Técnico
Name: Candidatura, dtype: str


In [17]:
import pandas as pd

excel_dados = pd.read_excel('C:/Python/excel_dados.xlsx')
entrevista=excel_dados[['Candidatura', 'Carimbo', 'Data', 'Hora']]
print (entrevista.head(2))
print (entrevista.tail(2))
print (entrevista)

   Candidatura    Carimbo       Data      Hora
0  Atendimento     Aceito 2026-02-15  12:55:25
1        Caixa  Rejeitado 2026-02-16  13:55:25
    Candidatura Carimbo       Data      Hora
8     Logistica  Aceito 2026-02-23  20:55:25
9  Almoxarifado  Aceito 2026-02-24  21:55:25
        Candidatura    Carimbo       Data      Hora
0       Atendimento     Aceito 2026-02-15  12:55:25
1             Caixa  Rejeitado 2026-02-16  13:55:25
2     Contabilidade  Rejeitado 2026-02-17  14:55:25
3   Suporte Técnico  Rejeitado 2026-02-18  15:55:25
4         Repositor     Aceito 2026-02-19  16:55:25
5     Suporte Redes  Rejeitado 2026-02-20  17:55:25
6       Programação  Rejeitado 2026-02-21  18:55:25
7  Manutenção de PC  Rejeitado 2026-02-22  19:55:25
8         Logistica     Aceito 2026-02-23  20:55:25
9      Almoxarifado     Aceito 2026-02-24  21:55:25


Trabalhar com  NumPy

In [18]:
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a+2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [19]:
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [20]:
a+2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [21]:
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
ax * 2

array([2, 4, 6, 8])

In [22]:
ax + 10

array([11, 12, 13, 14])

In [23]:
ax + ay

array([ 6,  8, 10, 12])

In [24]:
ax * ay

array([ 5, 12, 21, 32])

Trabalhando com numpy apartir de listas:

In [2]:

lista = [2,4,6,8,10]

In [1]:
import numpy as np
ar = np.array(lista)
dobro = 2*ar
print(dobro)

NameError: name 'lista' is not defined

Uso da Biblioteca matplotlib

In [ ]:
import matplotlib.pyplot as plt 
labels = 'Frogs','chickens', 'horses'

Testes Unitários - import unittest

In [ ]:
def remove_gatos(lista_gatos):
    
    while 'gato' in lista_gatos:
        lista_gatos.remove('gato')
    return lista_gatos

#lista1 = ['gato', 'cão', 'cobra', 'galinha', 'gato']
#lista2 = [1, 'gato', 3.5, 2, 'gato']

tuplo = (1, 'gato', 3.5, 2, 'gato')

#print(lista1)
#remove_gatos(lista1)
#print(lista1)

#remove_gatos(lista2)
#print(lista2)

#Tuplo não permite remover elementos - AttributeError: 'tuple' object has no attribute 'remove'
#  ( o uso da import Unittest serve para regular estes casos)
remove_gatos(tuplo)



AttributeError: 'tuple' object has no attribute 'remove'